/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCanvasIndexRouteImport } from './routes/app/canvas/index'
import { Route as ApiDbDocumentsRouteImport } from './routes/api/db/documents'
import { Route as ApiDbActiveRouteImport } from './routes/api/db/active'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as ApiDbDocumentsDocumentIdRouteImport } from './routes/api/db/documents.$documentId'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCanvasIndexRoute = AppCanvasIndexRouteImport.update({
  id: '/canvas/',
  path: '/canvas/',
  getParentRoute: () => AppRoute,
} as any)
const ApiDbDocumentsRoute = ApiDbDocumentsRouteImport.update({
  id: '/api/db/documents',
  path: '/api/db/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbActiveRoute = ApiDbActiveRouteImport.update({
  id: '/api/db/active',
  path: '/api/db/active',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbDocumentsDocumentIdRoute =
  ApiDbDocumentsDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => ApiDbDocumentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/app/': typeof AppIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/db/active': typeof ApiDbActiveRoute
  '/api/db/documents': typeof ApiDbDocumentsRouteWithChildren
  '/app/canvas/': typeof AppCanvasIndexRoute
  '/api/db/documents/$documentId': typeof ApiDbDocumentsDocumentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/app': typeof AppIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/db/active': typeof ApiDbActiveRoute
  '/api/db/documents': typeof ApiDbDocumentsRouteWithChildren
  '/app/canvas': typeof AppCanvasIndexRoute
  '/api/db/documents/$documentId': typeof ApiDbDocumentsDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/app/': typeof AppIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/db/active': typeof ApiDbActiveRoute
  '/api/db/documents': typeof ApiDbDocumentsRouteWithChildren
  '/app/canvas/': typeof AppCanvasIndexRoute
  '/api/db/documents/$documentId': typeof ApiDbDocumentsDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/mcp'
    | '/app/'
    | '/api/ai/chat'
    | '/api/db/active'
    | '/api/db/documents'
    | '/app/canvas/'
    | '/api/db/documents/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/app'
    | '/api/ai/chat'
    | '/api/db/active'
    | '/api/db/documents'
    | '/app/canvas'
    | '/api/db/documents/$documentId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/mcp'
    | '/app/'
    | '/api/ai/chat'
    | '/api/db/active'
    | '/api/db/documents'
    | '/app/canvas/'
    | '/api/db/documents/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiDbActiveRoute: typeof ApiDbActiveRoute
  ApiDbDocumentsRoute: typeof ApiDbDocumentsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/canvas/': {
      id: '/app/canvas/'
      path: '/canvas'
      fullPath: '/app/canvas/'
      preLoaderRoute: typeof AppCanvasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/db/documents': {
      id: '/api/db/documents'
      path: '/api/db/documents'
      fullPath: '/api/db/documents'
      preLoaderRoute: typeof ApiDbDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db/active': {
      id: '/api/db/active'
      path: '/api/db/active'
      fullPath: '/api/db/active'
      preLoaderRoute: typeof ApiDbActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db/documents/$documentId': {
      id: '/api/db/documents/$documentId'
      path: '/$documentId'
      fullPath: '/api/db/documents/$documentId'
      preLoaderRoute: typeof ApiDbDocumentsDocumentIdRouteImport
      parentRoute: typeof ApiDbDocumentsRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCanvasIndexRoute: typeof AppCanvasIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCanvasIndexRoute: AppCanvasIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiDbDocumentsRouteChildren {
  ApiDbDocumentsDocumentIdRoute: typeof ApiDbDocumentsDocumentIdRoute
}

const ApiDbDocumentsRouteChildren: ApiDbDocumentsRouteChildren = {
  ApiDbDocumentsDocumentIdRoute: ApiDbDocumentsDocumentIdRoute,
}

const ApiDbDocumentsRouteWithChildren = ApiDbDocumentsRoute._addFileChildren(
  ApiDbDocumentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiDbActiveRoute: ApiDbActiveRoute,
  ApiDbDocumentsRoute: ApiDbDocumentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
